### PR TITLE
Fixes for multiple issues

### PR DESCRIPTION
**Pull request by wbuchanan**
Should fix issue #4, issue #3, issue #2, and may fix issue #1.  The diffs below are larger than the should be.  This could be an issue related to doing the initial patching/fixes on a Windows machine before copying them to OSX.

### CODE REVIEW

**Comment by ClausKjaerPedersen** [comment]
Just tested it: 
 I receive a new error("} is not a valid command name"), which I think is connected to the 
"// Exit the program   
end" 
in line 84-85 :
2018-07-09 16_39_45-results
 I have tried to change the "end" to an "exit()".
This allows the part with dependencies to run(including installation of e.g. "tuples"), but it then reports another error (varlist not allowed). I can't identify the origin/source of this error...:
2018-07-09 16_38_28-results

Claus

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
Can you try to add:

```Stata
set tracedepth 3
set trace on
```

Before running the script.  You can copy/paste the output from the results window into the comments box instead of taking screenshots to make it a bit easier to sift through things as well.

**Comment by ClausKjaerPedersen** [comment]
Result from running the downloaded eda (with "end" within the dependencies package):
. sysuse auto.dta, clear
(1978 Automobile Data)
. set tracedepth 3
. set trace on
. eda, r(`"`c(pwd)'/edaexamples"') o("minexample") comp
} is not a valid command name
(error occurred while loading eda.ado)
r(199);
end of do-file
r(199);
.

**Comment by ClausKjaerPedersen** [comment]
Result from running eda ( after exchanging "end" with exit() within the dependencies package):
. sysuse auto.dta, clear
(1978 Automobile Data)
. set tracedepth 3
. set trace on
. eda, r(`"`c(pwd)'/edaexamples"') o("minexample") comp
  -------------------------------------------------------------------------------------------------------------------------------- begin eda ---
  - version 14
  - syntax [varlist] [using/] [if] [in], Output(string) Root(string) [ IDvars(varlist) STRok STRok2(varlist) MINNsize(passthru) MINCat(passthru)
>  MAXCat(passthru) CATVars(passthru) CONTVars(passthru) AUTHorname(string) REPOrtname(string) MISSing scheme(passthru) keepgph PERCent GRLABLen
> gth(passthru) noBARGRaphs BARGRAphopts(string asis) noPIECharts PIECHartopts(string asis) noHISTOgrams HISTOGramopts(string asis) KDENSity KDE
> NSOpts(string asis) FIVENUMsum FNSOpts(string asis) noDISTROplots DISTROPlotopts(string asis) noLADDERplots noSCATterplots LFIT LFIT2(string a
> sis) QFIT QFIT2(string asis) LOWess LOWess2(string asis) FPFIT FPFIT2(string asis) LFITCi LFITCi2(string asis) QFITCi QFITCi2(string asis) FPF
> ITCi FPFITCi2(string asis) noBUBBLEplots noBOXplots noMOSAIC noHEATmap COMPile PDFLatex(passthru) BYGraphs(string asis) BYVars(passthru) BYSeq
>  WEIGHTtype(passthru) ]
  - loc deps tuples spineplot estout
  - foreach d of loc deps {
  - cap which `d'
  = cap which tuples
  - if _rc != 0 {
    di as err "You do not have the dependency `d' installed on your machine."
    di "Would you like to install it from the SSC now? (Y/N)" _request(depcheck)
    while !inlist(`"$depcheck"', "y", "Y", "n", "N") {
    di "I'm sorry, I do not understand what you would like me to do."
    di "Would you like to install `d' from the SSC now? (Y/N)" _request(depcheck)
    }
    if inlist(`"$depcheck"', "y", "Y") ssc inst `d', replace
    else {
    di as err "This program cannot execute without its dependencies."
    di as err "The program will stop running now."
    exit()
    }
    }
  - }
  - cap which `d'
  = cap which spineplot
  - if _rc != 0 {
    di as err "You do not have the dependency `d' installed on your machine."
    di "Would you like to install it from the SSC now? (Y/N)" _request(depcheck)
    while !inlist(`"$depcheck"', "y", "Y", "n", "N") {
    di "I'm sorry, I do not understand what you would like me to do."
    di "Would you like to install `d' from the SSC now? (Y/N)" _request(depcheck)
    }
    if inlist(`"$depcheck"', "y", "Y") ssc inst `d', replace
    else {
    di as err "This program cannot execute without its dependencies."
    di as err "The program will stop running now."
    exit()
    }
    }
  - }
  - cap which `d'
  = cap which estout
  - if _rc != 0 {
    di as err "You do not have the dependency `d' installed on your machine."
    di "Would you like to install it from the SSC now? (Y/N)" _request(depcheck)
    while !inlist(`"$depcheck"', "y", "Y", "n", "N") {
    di "I'm sorry, I do not understand what you would like me to do."
    di "Would you like to install `d' from the SSC now? (Y/N)" _request(depcheck)
    }
    if inlist(`"$depcheck"', "y", "Y") ssc inst `d', replace
    else {
    di as err "This program cannot execute without its dependencies."
    di as err "The program will stop running now."
    exit()
    }
    }
  - }
  - glo depcheck ""
  - preserve
  - if `"`using'"' != "" qui: use `varlist' `"`using'"', clear
  = if `""' != "" qui: use make price mpg rep78 headroom trunk weight length turn displacement gear_ratio foreign `""', clear
  - marksample edause, strok novarlist
  - if "`percent'" == "" loc bartype count
  = if "" == "" loc bartype count
  - else loc bartype percent
  - if `"`authorname'"' == "" loc authorname `c(username)'
  = if `""' == "" loc authorname Claus Kjær Pedersen
  - if `"`reportname'"' == "" loc reportname $S_FN
  = if `""' == "" loc reportname C:\Program Files (x86)\Stata15\ado\base/a/auto.dta
  - loc root `: subinstr loc root "\" "/", all'
  = loc root C:/data/edaexamples
  - loc reportname `: subinstr loc reportname "\" "/", all'
  = loc reportname C:/Program Files (x86)/Stata15/ado/base/a/auto.dta
  - if "`slow'" != "" loc slow sleep 5000
  = if "" != "" loc slow sleep 5000
  - dirfile `root', p("graphs") rebuild
  = dirfile C:/data/edaexamples, p("graphs") rebuild
    -------------------------------------------------------------------------------------------------------------------------- begin dirfile ---
    - version 13
    - syntax , Path(string) [ REBuild ]
varlist not allowed
    ---------------------------------------------------------------------------------------------------------------------------- end dirfile ---
  ---------------------------------------------------------------------------------------------------------------------------------- end eda ---
r(101);
end of do-file
r(101);

**Pull request merged**
